tanshop/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->name('roles.')->controller(RoleController::class)->prefix('/roles')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:role-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:role-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:role-create');

    Route::get('/{id}/show', 'show')->name('show')
        ->middleware('check.permission:role-list');

    Route::get('/{id}/edit', 'edit')->name('edit')
        ->middleware('check.permission:role-edit');

    Route::put('/{id}/update', 'update')->name('update')
        ->middleware('check.permission:role-edit');

    Route::delete('/{id}/delete', 'destroy')->name('destroy')
        ->middleware('check.permission:role-delete');
});

Route::middleware(['auth'])->name('users.')->controller(UserController::class)->prefix('/users')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:user-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:user-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:user-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:user-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:user-edit');

    Route::put('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:user-edit');

    Route::delete('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:user-delete');
});

Route::middleware('auth')->name('products.')->controller(ProductController::class)->prefix('/products')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:product-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:product-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:product-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:product-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:product-edit');

    Route::post('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:product-edit');

    Route::get('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:product-delete');
});

Route::middleware('auth')->name('categories.')->controller(CategoryController::class)->prefix('/categories')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:category-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:category-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:category-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:category-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:category-edit');

    Route::put('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:category-edit');

    Route::delete('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:category-delete');
});

tanshop/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'products';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = ['name', 'price', 'image', 'description'];

    /**
     * The categories that belong to the products.
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_product');
    }

    /**
     * Scope a query to search products by name.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name', 'LIKE', '%' .$name . '%') : null;
    }

    /**
     * Scope a query to search products by price.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithPrice($query, $price)
    {
        return $price ? $query->where('price', '<=', $price) : null;
    }

    /**
     * Scope a query to search products by category.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeWithCategoryName($query, $categoryName)
    {
        return $categoryName ? $query->whereHas('categories', fn($query)
        => $query->where('name', 'LIKE', '%' .$categoryName . '%')) : null;
    }

    public function syncCategory($catID)
    {
        return $this->categories()->sync($catID);
    }
}

tanshop/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Product\StoreProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;
use App\Http\Resources\ProductResource;
use App\Services\CategoryService;
use App\Services\ProductService;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ProductController extends Controller
{
    /**
     * @var $productService
     * @var $categoryService
     */
    protected $productService;
    protected $categoryService;

    /**
     * ProductController constructor
     *
     * @param ProductService $productService
     * @param CategoryService $categoryService
     */
    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = $this->categoryService->getAll();
        $products = $this->productService->search($request);
        return view('products.index', compact('products', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $product = $this->productService->create($request);
        $productResource = new ProductResource($product);

        return $this->sentSuccessResponse($productResource, 'success', Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $product = $this->productService->findOrFail($id);
        $productResource = new ProductResource($product);

        return $this->sentSuccessResponse($productResource, 'success', Response::HTTP_OK);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $product = $this->productService->findOrFail($id);
        $productResource = new ProductResource($product);

        return $this->sentSuccessResponse($productResource, 'success', Response::HTTP_OK);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateProductRequest  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, int $id)
    {
        $product = $this->productService->update($request, $id);
        $productResource = new ProductResource($product);

        return $this->sentSuccessResponse($productResource, 'success', Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $productDeleted = $this->productService->delete($id);
        return response()->json(['success' => 'Delete Product Success !']);
    }
}

tanshop/resources/views/products/index.blade.php
@extends('layouts.theme')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-12">
                @if(session('success'))
                    <div class="alert alert-success">
                        <strong>{{session('success')}}</strong>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card card-plain">
                    <div class="card-header card-header-primary">
                        <h3 class="card-title text-center mt-0">PRODUCTS LIST</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-center my-3">
                            <div>
                                @permission('product-create')
                                <button type="button" name="create_product" id="create_product" data-route-store="{{ route('products.store') }}" class="btn btn-primary btn-sm create_product"><i class="fas fa-plus"></i> ADD</button>
                                @endpermission
                            </div>
                            <div class="card-tools">
                                <form action="{{ route('products.index') }}" method="GET" id="list-products" class="form-inline">
                                    <div class="form-group">
                                        <input type="number" class="form-control" id="price_ranger" name="price_ranger" min="0" max="60000000" value="{{$_GET['price_ranger'] ?? 0 }}" placeholder="Price">
                                    </div>

                                    <div class="form-group mx-sm-3">
                                        <input type="text" name="name" id="search_name" class="form-control" placeholder="Name" value="{{ $_GET['name'] ?? '' }}">
                                    </div>

                                    <div class="form-group">
                                        <select name="category_name" id="category_name" class="form-control">
                                            <option value="">Select Category</option>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category->name }}" {{ (isset($_GET['category_name']) && ($_GET['category_name'] == $category->name)) ? 'selected' : '' }}>{{ $category->name }}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group ml-3">
                                        <button type="submit" class="btn btn-default btn-sm"><i class="fas fa-search"></i></button>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div id="data_table">
                            <table id="user_table" class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Description</th>
                                        <th>Category</th>
                                        <th>Options</th>
                                    </tr>
                                </thead>
                                @foreach ($products as $product)
                                <tbody>
                                    <tr id="product_id_{{ $product->id }}">
                                        <td>
                                            {{ $product->id }}
                                        </td>
                                        <td>
                                            <img src="{{ '/images/' . $product->image }}" class="img-fluid" width="150" height="150" alt="image_default.png">
                                        </td>
                                        <td>
                                            {{ $product->name }}
                                        </td>
                                        <td>
                                            @convert($product->price) VNĐ
                                        </td>
                                        <td>
                                            {{ $product->description }}
                                        </td>
                                        <td>
                                            @foreach($product->categories as $category)
                                                <span class="badge rounded-pill bg-info text-dark">{{ $category->name }}</span>
                                            @endforeach
                                        </td>
                                        <td>
                                            @permission('product-edit')
                                            <a href="javascript:void(0)" data-id="{{ $product->id }}" data-toggle="modal" data-target="#formModal" data-route-edit="{{ route('products.edit', $product->id) }}" id="edit-product" data-route-update="{{ route('products.update', $product->id) }}" class="btn btn-warning btn-sm edit-product"><i class="fas fa-pencil"></i></a>
                                            @endpermission

                                            @permission('product-delete')
                                            <form id="deleteForm{{$product->id}}" method="POST" >
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                            <a href="javascript:void(0)" data-id="{{ $product->id }}" data-form="deleteForm{{$product->id}}" data-route-destroy="{{ route('products.destroy', $product->id) }}" id="delete-product" class="btn btn-danger btn-sm btn-delete delete-product"><i class="fas fa-trash"></i></a>
                                            @endpermission
                                        </td>
                                    </tr>
                                </tbody>
                                @endforeach
                            </table>
                            {{ $products->withQueryString()->links('pagination::bootstrap-4') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('products.modal')

@endsection

@section('script')
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="{{ asset('/assets/js/product/module.js') }}"></script>
    <script src="{{ asset('/assets/js/product/script.js') }}"></script>
    <script>
        $(function ()
        {
            $(document).on('click', '.btn-delete', function ()
            {
                let formID = $(this).data('form')
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(`#${formID}`).submit()
                        Swal.fire(
                            'Deleted!',
                            'This product has been deleted.',
                            'success'
                        )
                    }
                })
            })
        })
    </script>
@endsection

tanshop/resources/views/products/modal.blade.php
<div id="formModal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h4 class="modal-title">Add New Product</h4>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
            </div>

            <form method="POST" id="formSave" class="form-horizontal text-dark" enctype="multipart/form-data">
                @csrf
                <div class="modal-body bg-rose">
                    <div class="form-group">
                        <input type="hidden" name="id" id="id" class="form-control @error('id') is-invalid @enderror"/>
                        @error('id')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="name" class="text-primary">Name</label>
                        <input type="text" name="name" id="name" class="form-control text-dark @error('name') is-invalid @enderror"/>

                        @error('name')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="price" class="text-primary">Price</label>
                        <input type="number" name="price" id="price" class="form-control text-dark @error('price') is-invalid @enderror"/>

                        @error('price')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="description" class="text-primary">Description</label>
                        <textarea id="description" name="description" rows="3" class="form-control text-dark @error('description') is-invalid @enderror"></textarea>

                        @error('description')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="category_id" class="text-primary">Category</label>
                        <select id="category_id" name="category_id[]" class="selectpicker w-100 @error('category_id') is-invalid @enderror" multiple>
                            <option value="" selected>None</option>
                            @if($categories)
                                @foreach($categories as $value)
                                    <option value="{{$value->id}}">{{$value->name}}</option>
                                @endforeach
                            @endif
                        </select>
                        @error('category_id')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="image" class="text-primary">Select Image</label>
                        <input type="file" name="image" id="image" class="form-control text-dark @error('image') is-invalid @enderror"/>
                        <span id="store_image"></span>

                        @error('image')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="action" id="action" class="action" />
                    <input type="hidden" name="hidden_id" id="hidden_id" />
                    <input type="submit" name="action_button" id="action_button" class="btn btn-primary" value="Add" />
                    <a href="{{route('products.index')}}" class="btn btn-default">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>