tanshop/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->name('roles.')->controller(RoleController::class)->prefix('/roles')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:role-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:role-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:role-create');

    Route::get('/{id}/show', 'show')->name('show')
        ->middleware('check.permission:role-list');

    Route::get('/{id}/edit', 'edit')->name('edit')
        ->middleware('check.permission:role-edit');

    Route::put('/{id}/update', 'update')->name('update')
        ->middleware('check.permission:role-edit');

    Route::delete('/{id}/delete', 'destroy')->name('destroy')
        ->middleware('check.permission:role-delete');
});

Route::middleware(['auth'])->name('users.')->controller(UserController::class)->prefix('/users')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:user-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:user-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:user-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:user-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:user-edit');

    Route::put('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:user-edit');

    Route::delete('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:user-delete');
});

Route::middleware('auth')->name('products.')->controller(ProductController::class)->prefix('/products')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:product-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:product-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:product-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:product-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:product-edit');

    Route::post('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:product-edit');

    Route::get('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:product-delete');
});

Route::middleware('auth')->name('categories.')->controller(CategoryController::class)->prefix('/categories')->group(function ()
{
    Route::get('/', 'index')->name('index')
        ->middleware('check.permission:category-list');

    Route::get('/create', 'create')->name('create')
        ->middleware('check.permission:category-create');

    Route::post('/store', 'store')->name('store')
        ->middleware('check.permission:category-create');

    Route::get('/show/{id}', 'show')->name('show')
        ->middleware('check.permission:category-list');

    Route::get('/edit/{id}', 'edit')->name('edit')
        ->middleware('check.permission:category-edit');

    Route::put('/update/{id}', 'update')->name('update')
        ->middleware('check.permission:category-edit');

    Route::delete('/delete/{id}', 'destroy')->name('destroy')
        ->middleware('check.permission:category-delete');
});

tanshop/resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        @include('layouts.header')
    </head>
    <body class="dark-edition">
        <div class="wrapper">
            <div class="main-panel w-100">
                <!-- Navbar -->
                <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top" id="navigation-example">
                    @include('layouts.menu')
                </nav>
                <!-- End Navbar -->

                <!-- Content -->
                <div class="content">
                    @yield('content')
                </div>
                <!-- End Content -->

                <!-- Footer -->
                <footer class="footer">
                    @include('layouts.footer')
                </footer>
                <!-- End Footer -->
            </div>
        </div>

        @include('layouts.library')
    </body>
</html>

tanshop/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

tanshop/resources/views/layouts/footer.blade.php
<div class="container-fluid">
    <nav class="float-left">
        <ul>
            <li>
                <a href="#">DEHA ACADEMY</a>
            </li>
            <li>
                <a href="#">About Us</a>
            </li>
            <li>
                <a href="#">Blog</a>
            </li>
            <li>
                <a href="#">Licenses</a>
            </li>
        </ul>
    </nav>
    <div class="copyright float-right" id="date">
        , made with <i class="material-icons">favorite</i> by
        <a href="#" target="_blank">Thanh Tan</a> for a better web.
    </div>
</div>

tanshop/resources/views/layouts/header.blade.php
<meta charset="utf-8" />
<link rel="apple-touch-icon" sizes="76x76" href="{{asset('assets/img/apple-icon.png')}}">
<link rel="icon" type="image/png" href="{{asset('assets/img/favicon.png')}}">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<title>Material Dashboard</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
<!-- Fonts and icons -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
<!-- CSS Files -->
<link href="{{asset('assets/css/material-dashboard.css?v=2.1.0')}}" rel="stylesheet" />
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
<!-- CSS Just for demo purpose, don't include it in your project -->
<link href="{{asset('assets/demo/demo.css')}}" rel="stylesheet" />

tanshop/resources/views/layouts/library.blade.php
<!--   Core JS Files   -->
<script src="{{asset('assets/js/core/jquery.min.js')}}"></script>
<script src="{{asset('assets/js/core/popper.min.js')}}"></script>
<script src="{{asset('assets/js/core/bootstrap-material-design.min.js')}}"></script>
<script src="https://unpkg.com/default-passive-events"></script>
<script src="{{asset('assets/js/plugins/perfect-scrollbar.jquery.min.js')}}"></script>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Chartist JS -->
<script src="{{asset('assets/js/plugins/chartist.min.js')}}"></script>
<!--  Notifications Plugin    -->
<script src="{{asset('assets/js/plugins/bootstrap-notify.js')}}"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{asset('assets/js/material-dashboard.js?v=2.1.0')}}"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{{asset('assets/demo/demo.js')}}"></script>
{{--<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>--}}

<script src="{{ asset('js/app.js') }}" defer></script>
<script>
    $(document).ready(function() {
        $().ready(function() {
            $sidebar = $('.sidebar');

            $sidebar_img_container = $sidebar.find('.sidebar-background');

            $full_page = $('.full-page');

            $sidebar_responsive = $('body > .navbar-collapse');

            window_width = $(window).width();

            $('.fixed-plugin a').click(function(event) {
                // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
                if ($(this).hasClass('switch-trigger')) {
                    if (event.stopPropagation) {
                        event.stopPropagation();
                    } else if (window.event) {
                        window.event.cancelBubble = true;
                    }
                }
            });

            $('.fixed-plugin .active-color span').click(function() {
                $full_page_background = $('.full-page-background');

                $(this).siblings().removeClass('active');
                $(this).addClass('active');

                var new_color = $(this).data('color');

                if ($sidebar.length !== 0) {
                    $sidebar.attr('data-color', new_color);
                }

                if ($full_page.length !== 0) {
                    $full_page.attr('filter-color', new_color);
                }

                if ($sidebar_responsive.length !== 0) {
                    $sidebar_responsive.attr('data-color', new_color);
                }
            });

            $('.fixed-plugin .background-color .badge').click(function() {
                $(this).siblings().removeClass('active');
                $(this).addClass('active');

                var new_color = $(this).data('background-color');

                if ($sidebar.length !== 0) {
                    $sidebar.attr('data-background-color', new_color);
                }
            });

            $('.fixed-plugin .img-holder').click(function() {
                $full_page_background = $('.full-page-background');

                $(this).parent('li').siblings().removeClass('active');
                $(this).parent('li').addClass('active');


                var new_image = $(this).find("img").attr('src');

                if ($sidebar_img_container.length !== 0 && $('.switch-sidebar-image input:checked').length !== 0) {
                    $sidebar_img_container.fadeOut('fast', function() {
                        $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                        $sidebar_img_container.fadeIn('fast');
                    });
                }

                if ($full_page_background.length !== 0 && $('.switch-sidebar-image input:checked').length !== 0) {
                    var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                    $full_page_background.fadeOut('fast', function() {
                        $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                        $full_page_background.fadeIn('fast');
                    });
                }

                if ($('.switch-sidebar-image input:checked').length === 0) {
                    var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
                    var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

                    $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
                    $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
                }

                if ($sidebar_responsive.length !== 0) {
                    $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
                }
            });

            $('.switch-sidebar-image input').change(function() {
                $full_page_background = $('.full-page-background');

                $input = $(this);

                if ($input.is(':checked')) {
                    if ($sidebar_img_container.length !== 0) {
                        $sidebar_img_container.fadeIn('fast');
                        $sidebar.attr('data-image', '#');
                    }

                    if ($full_page_background.length !== 0) {
                        $full_page_background.fadeIn('fast');
                        $full_page.attr('data-image', '#');
                    }

                    background_image = true;
                } else {
                    if ($sidebar_img_container.length !== 0) {
                        $sidebar.removeAttr('data-image');
                        $sidebar_img_container.fadeOut('fast');
                    }

                    if ($full_page_background.length !== 0) {
                        $full_page.removeAttr('data-image', '#');
                        $full_page_background.fadeOut('fast');
                    }

                    background_image = false;
                }
            });

            $('.switch-sidebar-mini input').change(function() {
                $body = $('body');

                $input = $(this);

                if (md.misc.sidebar_mini_active === true) {
                    $('body').removeClass('sidebar-mini');
                    md.misc.sidebar_mini_active = false;

                    $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

                } else {

                    $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

                    setTimeout(function() {
                        $('body').addClass('sidebar-mini');

                        md.misc.sidebar_mini_active = true;
                    }, 300);
                }

                // we simulate the window Resize so the charts will get updated in realtime.
                var simulateWindowResize = setInterval(function() {
                    window.dispatchEvent(new Event('resize'));
                }, 180);

                // we stop the simulation of Window Resize after the animations are completed
                setTimeout(function() {
                    clearInterval(simulateWindowResize);
                }, 1000);

            });
        });
    });
</script>
<script>
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();
    });
</script>
<script>
    const x = new Date().getFullYear();
    let date = document.getElementById('date');
    date.innerHTML = '&copy; ' + x + date.innerHTML;
</script>
@yield('script')

tanshop/resources/views/layouts/main.blade.php
<div class="main-panel">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top" id="navigation-example">
        @include('layouts.menu')
    </nav>
    <!-- End Navbar -->

    <!-- Content -->
    <div class="content">
        @yield('content')
    </div>
    <!-- End Content -->

    <!-- Footer -->
    <footer class="footer">
        @include('layouts.footer')
    </footer>
    <!-- End Footer -->
</div>

tanshop/resources/views/layouts/menu.blade.php
<div class="container-fluid">
    <div class="navbar-wrapper">
        <a class="navbar-brand" href="javascript:void(0)">Dashboard</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
        <span class="sr-only">Toggle navigation</span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
        <span class="navbar-toggler-icon icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end">
        <ul class="navbar-nav">
            <!-- Authentication Links -->
            @guest
                @if (Route::has('login'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                @endif

                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        {{ Auth::user()->name }}
                    </a>

                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</div>

tanshop/resources/views/layouts/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="black" data-image="{{asset('assets/img/sidebar-2.jpg')}}">
    <div class="logo">
        <a href="{{route('home')}}" class="simple-text logo-normal">DEHA ACADEMY</a>
    </div>
    <div class="sidebar-wrapper">
        <ul class="nav">
            @guest
                @if (Route::has('home'))
                    <li class="nav-item active">
                        <a class="nav-link" href="{{route('home')}}">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                @endif
            @else
                @if (Auth::user()->hasPermission('user-list'))
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('users.index')}}">
                            <i class="material-icons">person</i>
                            <p>User Manager</p>
                        </a>
                    </li>
                @endif

                @if (Auth::user()->hasPermission('role-list'))
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('roles.index')}}">
                            <i class="material-icons">content_paste</i>
                            <p>Role Manager</p>
                        </a>
                    </li>
                @endif

                @if (Auth::user()->hasPermission('category-list'))
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('categories.index')}}">
                            <i class="material-icons">library_books</i>
                            <p>Category Manager</p>
                        </a>
                    </li>
                @endif

                @if (Auth::user()->hasPermission('product-list'))
                    <li class="nav-item ">
                        <a class="nav-link" href="{{route('products.index')}}">
                            <i class="material-icons">bubble_chart</i>
                            <p>Product Manager</p>
                        </a>
                    </li>
                @endif
            @endguest
        </ul>
    </div>
</div>

tanshop/resources/views/layouts/theme.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        @include('layouts.header')
    </head>
    <body class="dark-edition">
        <div class="wrapper">
            @include('layouts.sidebar')
            @include('layouts.main')
        </div>
        <div class="library">
            @include('layouts.library')
        </div>
    </body>
</html>